mode: auto
silent: false
branchName: '${issue.number}-${issue.title}'
branches:
  - label: '✨ Feature'
    prefix: feature/
  - label: '🐞 BugFix'
    prefix: bugfix/
  - label: '📃 Docs'
    prefix: docs/
  - label: '🔨 Refactor'
    prefix: refactor/
  - label: '🎨 Publish'
    prefix: publish/
  - label: '📬 API'
    prefix: api/
  - label: '📝 Modify'
    prefix: modify/
  - label: '💻 CrossBrowsing'
    prefix: cross-browsing/
  - label: '⚙ Setting'
    prefix: setting/
  - label: '🌏 Deploy'
    prefix: deploy/
  - label: '*'
    prefix: issue/
